# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/model_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pp/model_service.proto\x12\x05model\"\x8a\x01\n\x0cTrainRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x06params\x18\x02 \x03(\x0b\x32\x1f.model.TrainRequest.ParamsEntry\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x1f\n\rTrainResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\r\n\x0bListRequest\"\x1e\n\x0cListResponse\x12\x0e\n\x06models\x18\x01 \x03(\t\"0\n\x0ePredictRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\"\x1f\n\x0fPredictResponse\x12\x0c\n\x04pred\x18\x01 \x01(\x02\x32\xb8\x01\n\x0cModelService\x12\x37\n\nTrainModel\x12\x13.model.TrainRequest\x1a\x14.model.TrainResponse\x12\x35\n\nListModels\x12\x12.model.ListRequest\x1a\x13.model.ListResponse\x12\x38\n\x07Predict\x12\x15.model.PredictRequest\x1a\x16.model.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_TRAINREQUEST']._serialized_start=35
  _globals['_TRAINREQUEST']._serialized_end=173
  _globals['_TRAINREQUEST_PARAMSENTRY']._serialized_start=128
  _globals['_TRAINREQUEST_PARAMSENTRY']._serialized_end=173
  _globals['_TRAINRESPONSE']._serialized_start=175
  _globals['_TRAINRESPONSE']._serialized_end=206
  _globals['_LISTREQUEST']._serialized_start=208
  _globals['_LISTREQUEST']._serialized_end=221
  _globals['_LISTRESPONSE']._serialized_start=223
  _globals['_LISTRESPONSE']._serialized_end=253
  _globals['_PREDICTREQUEST']._serialized_start=255
  _globals['_PREDICTREQUEST']._serialized_end=303
  _globals['_PREDICTRESPONSE']._serialized_start=305
  _globals['_PREDICTRESPONSE']._serialized_end=336
  _globals['_MODELSERVICE']._serialized_start=339
  _globals['_MODELSERVICE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
